CREATE TABLE IF NOT EXISTS quiz_questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  difficulty ENUM('Beginner','Intermediate','Advanced') NOT NULL,
  question TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option CHAR(1) NOT NULL
);

INSERT INTO quiz_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_option) VALUES
('Python Basics', 'Beginner', 'Which keyword is used to define a function in Python?', 'func', 'define', 'def', 'lambda', 'C'),
('Python Basics', 'Beginner', 'Which of these data types is mutable?', 'tuple', 'string', 'list', 'int', 'C'),
('Python Basics', 'Beginner', 'What does type(5) return?', 'float', 'str', 'int', 'bool', 'C'),
('Python Basics', 'Beginner', 'Which symbol is used for comments in Python?', '//', '#', '/*', '--', 'B'),
('Python Basics', 'Beginner', 'Which operator is used for exponentiation?', '+', '^', '**', '%', 'C'),
('Python Basics', 'Intermediate', 'What is the output of len([1, 2, 3])?', '2', '3', '4', '5', 'B'),
('Python Basics', 'Intermediate', 'Which function opens a file in read mode?', 'open(''file.txt'',''r'')', 'read(''file.txt'')', 'file.open(''r'')', 'load(''file.txt'')', 'A'),
('Python Basics', 'Intermediate', 'What does ''abc''.upper() return?', 'abc', 'Abc', 'ABC', 'aBc', 'C'),
('Python Basics', 'Intermediate', 'Which data type stores key-value pairs?', 'list', 'set', 'dict', 'tuple', 'C'),
('Python Basics', 'Intermediate', 'What does list(range(3)) produce?', '[1, 2, 3]', '[0, 1, 2]', '[0, 1, 2, 3]', '[3, 2, 1]', 'B'),
('Python Basics', 'Advanced', 'What is a decorator in Python?', 'A built-in loop type', 'A function that modifies another function', 'A type of class variable', 'A file handling method', 'B'),
('Python Basics', 'Advanced', 'What is the purpose of if __name__ == ''__main__'':?', 'It imports modules automatically', 'It prevents syntax errors', 'It runs code only when the file is executed directly', 'It defines a main class', 'C'),
('Python Basics', 'Advanced', 'What do *args collect in a function?', 'Keyword arguments', 'Positional arguments', 'Global variables', 'Default values', 'B'),
('Python Basics', 'Advanced', 'What is a generator?', 'A function that returns a list immediately', 'An iterator that yields values lazily', 'A class with no methods', 'A loop that runs forever', 'B'),
('Python Basics', 'Advanced', 'What is a shallow copy?', 'A copy that duplicates nested objects too', 'A copy that shares nested references', 'A copy that cannot be modified', 'A copy made only from tuples', 'B'),
('Web Development', 'Beginner', 'What does HTML stand for?', 'HyperText Markup Language', 'HighText Machine Language', 'HyperTool Multi Language', 'Home Tool Markup Language', 'A'),
('Web Development', 'Beginner', 'Which language is used to style web pages?', 'Python', 'CSS', 'SQL', 'PHP', 'B'),
('Web Development', 'Beginner', 'Which tag creates a hyperlink?', '<link>', '<a>', '<href>', '<p>', 'B'),
('Web Development', 'Beginner', 'What does HTTP stand for?', 'HyperText Transfer Protocol', 'High Transfer Text Protocol', 'HyperText Translation Process', 'Home Tool Transfer Protocol', 'A'),
('Web Development', 'Beginner', 'Which language runs in the browser for interactivity?', 'Java', 'JavaScript', 'C++', 'Python', 'B'),
('Web Development', 'Intermediate', 'Which HTTP method is commonly used to submit form data?', 'GET', 'POST', 'PATCH', 'TRACE', 'B'),
('Web Development', 'Intermediate', 'What does DOM stand for?', 'Data Object Model', 'Document Object Model', 'Dynamic Object Mapping', 'Digital Output Machine', 'B'),
('Web Development', 'Intermediate', 'Which CSS layout model uses display: flex?', 'Grid', 'Flexible Box Layout', 'Float Layout', 'Block Layout', 'B'),
('Web Development', 'Intermediate', 'Which HTML element is semantic for page navigation?', 'section', 'article', 'nav', 'aside', 'C'),
('Web Development', 'Intermediate', 'What is localStorage used for?', 'Server-side database', 'Temporary session on backend', 'Browser storage that persists data', 'Rendering HTML templates', 'C'),
('Web Development', 'Advanced', 'What does CORS mean?', 'Cross-Origin Resource Sharing', 'Central Origin Routing System', 'Client-Oriented Request Security', 'Cross Object Response Service', 'A'),
('Web Development', 'Advanced', 'What is a Single Page Application (SPA)?', 'A site with only one image', 'An app that reloads the whole page every click', 'An app that updates views without full page reloads', 'A website with a single HTML tag', 'C'),
('Web Development', 'Advanced', 'What is event delegation?', 'Adding a listener to every child element', 'Handling events on a parent element for its children', 'Removing all event listeners', 'Using CSS instead of JavaScript', 'B'),
('Web Development', 'Advanced', 'What is the main difference between SSR and CSR?', 'SSR uses server-side rendering; CSR uses client-side rendering', 'SSR uses CSS; CSR uses HTML', 'SSR is for mobile only', 'CSR cannot use JavaScript', 'A'),
('Web Development', 'Advanced', 'What does REST API primarily expose?', 'UI components', 'Resources through HTTP endpoints', 'Database indexes', 'Local browser cache', 'B'),
('Data Science', 'Beginner', 'What is the mean of 2, 4, 6, 8?', '4', '5', '6', '7', 'B'),
('Data Science', 'Beginner', 'Which library is commonly used for data manipulation in Python?', 'NumPy', 'Pandas', 'Matplotlib', 'Flask', 'B'),
('Data Science', 'Beginner', 'What does CSV stand for?', 'Common Separate Values', 'Comma-Separated Values', 'Column Split Values', 'Computed System Variables', 'B'),
('Data Science', 'Beginner', 'What is missing data often called?', 'Null handling', 'Imputation', 'Regression', 'Clustering', 'B'),
('Data Science', 'Beginner', 'Which data structure is NumPy built around?', 'Arrays', 'Graphs', 'Queues', 'Trees', 'A'),
('Data Science', 'Intermediate', 'What does standard deviation measure?', 'Center of data', 'Spread of data', 'Number of categories', 'File size', 'B'),
('Data Science', 'Intermediate', 'Why do we use train/test split?', 'To compress files', 'To estimate performance on unseen data', 'To increase memory', 'To remove labels', 'B'),
('Data Science', 'Intermediate', 'What does correlation describe?', 'Cause and effect', 'Relationship between variables', 'Data encryption', 'Sorting order', 'B'),
('Data Science', 'Intermediate', 'What is one-hot encoding used for?', 'Reducing noise', 'Representing categorical variables numerically', 'Normalizing dates', 'Deleting duplicates', 'B'),
('Data Science', 'Intermediate', 'Which chart is useful for showing distribution and outliers?', 'Pie chart', 'Box plot', 'Line chart', 'Heatmap', 'B'),
('Data Science', 'Advanced', 'What does a p-value help assess?', 'Model file size', 'Evidence against a null hypothesis', 'The number of classes', 'The dataset shape', 'B'),
('Data Science', 'Advanced', 'What is the bias-variance tradeoff?', 'Balance between underfitting and overfitting', 'Choice between SQL and NoSQL', 'Comparison of two datasets', 'A method for scaling features', 'A'),
('Data Science', 'Advanced', 'Why is cross-validation used?', 'To shorten training time only', 'To estimate generalization more reliably', 'To encrypt data', 'To remove missing values', 'B'),
('Data Science', 'Advanced', 'What is overfitting?', 'Model performs well on training data but poorly on new data', 'Model cannot learn at all', 'Model only works on images', 'Model uses too much RAM', 'A'),
('Data Science', 'Advanced', 'Why is feature scaling often needed?', 'To change the target label', 'To normalize different value ranges', 'To increase category count', 'To remove duplicates', 'B'),
('Machine Learning', 'Beginner', 'What is supervised learning?', 'Learning without any data', 'Learning from labeled data', 'Learning from random guesses', 'Learning only from images', 'B'),
('Machine Learning', 'Beginner', 'What does classification predict?', 'Continuous values', 'Discrete categories or labels', 'File names', 'Clusters only', 'B'),
('Machine Learning', 'Beginner', 'What does regression predict?', 'Continuous values', 'Binary labels', 'Text tokens', 'Image pixels only', 'A'),
('Machine Learning', 'Beginner', 'What is overfitting?', 'When a model generalizes too well', 'When a model performs well on training data but poorly on test data', 'When a model has no parameters', 'When a model is unsupervised', 'B'),
('Machine Learning', 'Beginner', 'K-means is an example of which type of learning?', 'Supervised learning', 'Reinforcement learning', 'Clustering', 'Dimensionality reduction', 'C'),
('Machine Learning', 'Intermediate', 'What is gradient descent used for?', 'Feature engineering', 'Optimization', 'Data cleaning', 'Label encoding', 'B'),
('Machine Learning', 'Intermediate', 'What does a loss function measure?', 'Model speed', 'Prediction error', 'Dataset size', 'Number of features', 'B'),
('Machine Learning', 'Intermediate', 'What is a random forest?', 'A single decision tree', 'An ensemble of decision trees', 'A clustering algorithm', 'A neural network layer', 'B'),
('Machine Learning', 'Intermediate', 'How is precision defined?', 'TP / (TP + FN)', 'TP / (TP + FP)', 'TN / (TN + FP)', 'FP / (TP + FP)', 'B'),
('Machine Learning', 'Intermediate', 'How is recall defined?', 'TP / (TP + FN)', 'TP / (TP + FP)', 'TN / (TN + FN)', 'FP / (FN + TP)', 'A'),
('Machine Learning', 'Advanced', 'What does regularization help control?', 'Model complexity', 'File format', 'Label count', 'Class names', 'A'),
('Machine Learning', 'Advanced', 'What does ROC-AUC measure?', 'Training speed', 'Ranking quality across thresholds', 'Dataset size', 'Number of features', 'B'),
('Machine Learning', 'Advanced', 'What is a hyperparameter?', 'A parameter learned directly from data', 'A setting chosen before training', 'A type of loss function', 'A feature column', 'B'),
('Machine Learning', 'Advanced', 'What does bagging mainly reduce?', 'Bias', 'Variance', 'Class labels', 'Dataset size', 'B'),
('Machine Learning', 'Advanced', 'Why is early stopping used?', 'To increase overfitting', 'To prevent overfitting by stopping training when validation worsens', 'To remove outliers', 'To shuffle labels', 'B'),
('Cybersecurity', 'Beginner', 'Which is the strongest password choice?', 'password123', 'Your name plus birth year', 'A long random password', 'qwerty', 'C'),
('Cybersecurity', 'Beginner', 'What is phishing?', 'A backup method', 'A scam to trick users into revealing information', 'A firewall rule', 'A type of encryption', 'B'),
('Cybersecurity', 'Beginner', 'What does antivirus software do?', 'Designs websites', 'Detects and removes malware', 'Compresses files', 'Creates passwords', 'B'),
('Cybersecurity', 'Beginner', 'What is a firewall used for?', 'Rendering web pages', 'Filtering network traffic', 'Encrypting hard drives', 'Writing code', 'B'),
('Cybersecurity', 'Beginner', 'What does MFA stand for?', 'Multiple File Access', 'Multi-Factor Authentication', 'Main Firewall Adapter', 'Managed Fraud Alert', 'B'),
('Cybersecurity', 'Intermediate', 'What does encryption do?', 'Deletes files', 'Converts plaintext into ciphertext', 'Monitors system logs', 'Blocks ads only', 'B'),
('Cybersecurity', 'Intermediate', 'What is SQL injection?', 'A database backup', 'A code attack that manipulates SQL queries', 'A login method', 'A file compression technique', 'B'),
('Cybersecurity', 'Intermediate', 'What does least privilege mean?', 'Give every user admin access', 'Give only the minimum access needed', 'Store passwords in plain text', 'Share one account for all users', 'B'),
('Cybersecurity', 'Intermediate', 'What is hashing?', 'A two-way encryption method', 'A one-way transformation of data', 'A way to hide servers', 'A network routing protocol', 'B'),
('Cybersecurity', 'Intermediate', 'What protocol is used by HTTPS?', 'TLS', 'FTP', 'SMTP', 'SSH', 'A'),
('Cybersecurity', 'Advanced', 'What is a zero-day vulnerability?', 'A bug already patched everywhere', 'A vulnerability unknown to the defender or not yet patched', 'A password reset feature', 'A safe coding standard', 'B'),
('Cybersecurity', 'Advanced', 'What is XSS?', 'Cross-Site Scripting', 'Extra Secure System', 'Extended Server Storage', 'Cross System Signing', 'A'),
('Cybersecurity', 'Advanced', 'What can a buffer overflow cause?', 'Only slow loading', 'Memory corruption or code execution', 'Better encryption', 'Automatic patching', 'B'),
('Cybersecurity', 'Advanced', 'What is penetration testing?', 'Random malware deployment', 'Simulating attacks to find weaknesses before real attackers do', 'Deleting logs', 'Changing user passwords', 'B'),
('Cybersecurity', 'Advanced', 'What does defense in depth mean?', 'One strong password is enough', 'Layering multiple security controls', 'Using only antivirus', 'Turning off the firewall', 'B');